---
- name: Install Logstash on Ubuntu
  apt:
    name: logstash
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Logstash on CentOs
  yum:
    name: logstash
    state: present
  when: ansible_distribution == 'CentOS'
